import { useState, useEffect } from 'react'
import './App.css'

function App() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    // Fetch data.json dynamically
    // GitHub Pages will serve from /newsai/data.json
    // Dev server will serve from /data.json if in public, but let's try relative and root.
    const fetchUrl = import.meta.env.BASE_URL + 'data.json';
    
    fetch(fetchUrl)
      .then((res) => {
        if (!res.ok) throw new Error('데이터를 불러오는데 실패했습니다.')
        return res.json()
      })
      .then((json) => {
        setData(json)
        setLoading(false)
      })
      .catch((err) => {
        console.error(err)
        // Fallback for dev environment
        fetch('/data.json')
            .then(res => res.json())
            .then(json => {
                setData(json);
                setLoading(false);
            })
            .catch(e => {
                setError(err.message)
                setLoading(false)
            });
      })
  }, [])

  if (loading) {
    return <div className="loading-container">데이터를 불러오는 중...</div>
  }

  if (error) {
    return <div className="error-container">에러: {error}</div>
  }

  if (!data || !data.news) {
    return <div className="error-container">데이터가 없습니다.</div>
  }

  return (
    <div className="container">
      <header>
        <div className="logo">NewSai 🤖</div>
        <h1>AI 데일리 리포트</h1>
        <p className="date">발행일: <span id="report-date">{data.reportDate}</span></p>
        <div className="actions">
          <a href={import.meta.env.BASE_URL + 'report.pdf'} className="btn-download" download>PDF 리포트 다운로드</a>
        </div>
      </header>

      <main>
        <section className="summary-section">
          <h2>오늘의 요약</h2>
          <div className="summary-content">{data.summary}</div>
        </section>

        <section className="news-section">
          <h2>주요 뉴스 목록</h2>
          <div className="news-list">
            {data.news.map((item, index) => (
              <div className="news-card" key={index}>
                <span className="pub-date">{new Date(item.pubDate).toLocaleDateString()}</span>
                <h3><a href={item.link} target="_blank" rel="noopener noreferrer">{item.title}</a></h3>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer>
        <p>&copy; 2026 NewSai Automation. Generated by LLM.</p>
        <p>
          <a href="https://github.com/dragon-it/newsai">GitHub Repository</a>
        </p>
      </footer>
    </div>
  )
}

export default App
